model_name: "model_0526.pt"
dt: 0.005
decimation: 4
num_observations: 45
clip_obs: 100.0
clip_actions_lower: [-100, -100, -100, 
                      -100, -100, -100, 
                      -100, -100, -100, 
                      -100, -100, -100] 
clip_actions_upper: [100, 100, 100, 
                      100, 100, 100, 
                      100, 100, 100, 
                      100, 100, 100] 
# rl_kp: [40, 40, 80, 80, 5, 5, 
#         40, 40, 80, 80, 5, 5] 
rl_kp: [40, 40, 80, 80, 60, 60, 
        40, 40, 80, 80, 60, 60] 
# rl_kp: [0, 0, 0, 0, 0, 0, 
#         0, 0, 0, 0, 0, 0] 
rl_kd: [0.9, 0.9, 0.9, 0.9, 0.25, 0.25, 
        0.9, 0.9, 0.9, 0.9, 0.25, 0.25]

hip_scale_reduction: 0.5
hip_scale_reduction_indices: [0, 3, 6, 9]
num_of_dofs: 12
action_scale: 0.25
lin_vel_scale: 2.0
ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
commands_scale: [2.0, 2.0, 1.0]
torque_limits: [33.5, 33.5, 33.5, 
                33.5, 33.5, 33.5, 
                33.5, 33.5, 33.5, 
                33.5, 33.5, 33.5]   
default_dof_pos: [0.0, 0.0, -0.40, -0.60, -0.40, 0.0, 
                  0.0, 0.0, 0.40, 0.60, 0.40, 0.0]             
                  
init_dof_pos: [0.0, 0.0, -0.35, -0.70, -0.55, 0.0, 
               0.0, 0.0, 0.35, 0.70, 0.35, -0.0]
# init_dof_pos: [0.0, 0.0, -0.095, 
#                 -0.50, -0.30, 0.0, 
#                 0.0, 0.0, 0.095, 
#                 0.50, 0.30, -0.0]
# joint_controller_names: ["FL_hip_controller", "FL_thigh_controller", "FL_calf_controller",
#                           "FR_hip_controller", "FR_thigh_controller", "FR_calf_controller",
#                           "RL_hip_controller", "RL_thigh_controller", "RL_calf_controller",
#                           "RR_hip_controller", "RR_thigh_controller", "RR_calf_controller"]
